### ISSUE TITLE
Making the Slack class its own plugin

### ISSUE THREAD

**Issue by ericadestoya** [BallStateCBER/deploy#1]
I might go ahead and make the Slack class its own plugin, that way it can just be composer-ed by the other apps that use it. Now that we'll be using it on the commentaries site, as well as I think I might use it on ME 3.x to confirm that events mails are sent. Ja?

**Comment by PhantomWatson** [comment]
Since sending messages to Slack is as simple as a cURL call, a Slack messaging class would be pretty trivial (example: https://github.com/BallStateCBER/economic-indicators-cakephp4/blob/master/src/Slack/Slack.php) and maybe not worth making into its own plugin.
